# Generated by Django 6.1.1 on 2026-10-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0005_alter_student_options_remove_courses_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='email',
            new_name='password',
        ),
    ]
