# Generated by Django 6.0.4 on 2026-08-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Sagird', 'verbose_name_plural': 'Sagirdler'},
        ),
    ]
