# Generated by Django 6.0.4 on 2026-08-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=0, upload_to='students/'),
            preserve_default=False,
        ),
    ]
