# Generated by Django 6.0.4 on 2026-08-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
