# Generated by Django 6.1.1 on 2026-09-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
